# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for generate_examples.py."""

import os
import pathlib
import tempfile
from typing import Any, List, Tuple
from absl.testing import absltest

from apache_beam.testing import test_pipeline
from apache_beam.testing.util import assert_that
import numpy as np
from skai import generate_examples
from skai import utils
import tensorflow as tf

TEST_IMAGE_PATH = 'test_data/blank.tif'


def _deserialize_image(serialized_image: bytes) -> np.ndarray:
  return tf.io.decode_image(serialized_image).numpy()


def _unordered_all_close(list1: List[Any], list2: List[Any]) -> bool:
  """Return that two lists of coordinates are close to each other."""
  if len(list1) != len(list2):
    return False

  sorted_list1 = sorted(list1)
  sorted_list2 = sorted(list2)
  return np.allclose(sorted_list1, sorted_list2)


def _check_serialized_examples(
    expected_patch_size: int,
    expected_coordinates: List[Tuple[float, float, float]],
    expect_blank_before: bool):
  """Validates examples generated from beam pipeline.

  Args:
    expected_patch_size: The expected size of encoded patches.
    expected_coordinates: List of coordinates that examples should have.
    expect_blank_before: If true, the before image should be all zeros.

  Returns:
    Function for validating examples.
  """

  def _check_examples(actual_serialized_examples):
    actual_coordinates = set()
    expected_shape = (expected_patch_size, expected_patch_size, 3)

    for serialized in actual_serialized_examples:
      example = tf.train.Example()
      example.ParseFromString(serialized)
      feature_names = set(example.features.feature.keys())
      # TODO(jzxu): Use constants for these feature name strings.
      assert feature_names == set([
          'pre_image_png', 'post_image_png', 'coordinates',
          'encoded_coordinates', 'label'
      ]), f'Feature set does not match. Got: {" ".join(feature_names)}'

      longitude, latitude = (
          example.features.feature['coordinates'].float_list.value)
      label = example.features.feature['label'].float_list.value[0]

      before_image = _deserialize_image(
          example.features.feature['pre_image_png'].bytes_list.value[0])
      assert before_image.shape == expected_shape, (
          f'Expected before image shape = {expected_shape}, '
          f'actual = {before_image.shape}')
      if expect_blank_before:
        assert not before_image.any(), 'Expected blank before image.'
      else:
        assert before_image.any(), 'Expected non-blank before image.'

      after_image = _deserialize_image(
          example.features.feature['post_image_png'].bytes_list.value[0])
      assert after_image.shape == expected_shape, (
          f'Expected after image shape = {expected_shape}, '
          f'actual = {after_image.shape}')

      actual_coordinates.add((longitude, latitude, label))

    assert _unordered_all_close(expected_coordinates, actual_coordinates)

  return _check_examples


def _check_labeling_images(expected_width: int,
                           expected_height: int,
                           expected_coordinates: List[Tuple[float, float]]):
  """Validates labeling images generated by beam pipeline.

  Args:
    expected_width: The expected size of encoded patches.
    expected_height: The expected size of encoded patches.
    expected_coordinates: List of coordinates that examples should have.

  Returns:
    Function for validating examples.
  """

  def _check_images(actual_serialized_images):
    actual_coordinates = set()
    for name, serialized_image in actual_serialized_images:
      assert name.endswith('.png'), f'File {name} does not end with .png'
      encoded_coords = name[:-4]  # Remove ".png" suffix.
      longitude, latitude = utils.decode_coordinates(encoded_coords)
      actual_coordinates.add((longitude, latitude))
      image = _deserialize_image(serialized_image)
      assert image.shape == (expected_height, expected_width,
                             3), f'Unexpected shape {image.shape}'

    assert _unordered_all_close(expected_coordinates, actual_coordinates), (
        f'Coordinates different. Expected "{expected_coordinates}", '
        f'Actual "{actual_coordinates}".')

  return _check_images


class GenerateExamplesTest(absltest.TestCase):

  def setUp(self):
    super().setUp()
    current_dir = pathlib.Path(__file__).parent
    self.test_image_path = str(current_dir / TEST_IMAGE_PATH)

  def testGenerateExamplesFn(self):
    """Tests GenerateExamplesFn class."""

    unlabeled_coordinates = [(178.482925, -16.632893),
                             (178.482283, -16.632279)]

    with test_pipeline.TestPipeline() as pipeline:
      examples, labeling_images = generate_examples._generate_examples(
          pipeline, self.test_image_path, self.test_image_path, 62, 32, 0.5,
          unlabeled_coordinates, [], 1, {}, 'unlabeled')

      # Example at second input coordinate should be dropped because its patch
      # falls mostly outside the before and after image bounds.
      assert_that(examples, _check_serialized_examples(
          32, [(178.482925, -16.632893, -1.0)], False), label='assert_examples')

      expected_width = 154   # 62 + 62 + 10 * 3
      expected_height = 114  # 62 + 2 * 10 + height for caption
      assert_that(
          labeling_images,
          _check_labeling_images(expected_width, expected_height,
                                 [(178.482925, -16.632893)]),
          label='assert_labeling_images')

  def testGenerateExamplesFnLabeled(self):
    """Tests GenerateExamplesFn class."""

    labeled_coordinates = [(178.482925, -16.632893, 0),
                           (178.482924, -16.632894, 1)]

    with test_pipeline.TestPipeline() as pipeline:
      examples, _ = generate_examples._generate_examples(
          pipeline, self.test_image_path, self.test_image_path, 62, 32, 0.5,
          [], labeled_coordinates, 0.0, {}, 'labeled')

      assert_that(examples, _check_serialized_examples(
          32, [(178.482925, -16.632893, 0.0), (178.482924, -16.632894, 1.0)],
          False), label='assert_examples')

  def testGenerateExamplesFnNoBefore(self):
    """Tests GenerateExamplesFn class without before image."""

    coordinates = [(178.482925, -16.632893), (178.482283, -16.632279)]

    with test_pipeline.TestPipeline() as pipeline:
      examples, labeling_images = generate_examples._generate_examples(
          pipeline, '', self.test_image_path, 62, 32, 0.5, coordinates, [], 1,
          {}, 'unlabeled')

      # Example at second input coordinate should be dropped because its patch
      # falls mostly outside the before and after image bounds.
      assert_that(examples, _check_serialized_examples(
          32, [(178.482925, -16.632893, -1.0)], True), label='assert_examples')

      expected_width = 154   # 62 + 62 + 10 * 3
      expected_height = 114  # 62 + 2 * 10 + height for caption
      assert_that(
          labeling_images,
          _check_labeling_images(expected_width, expected_height,
                                 [(178.482925, -16.632893)]),
          label='assert_labeling_images')

  def testGenerateExamplesPipeline(self):
    output_dir = tempfile.mkdtemp(dir=absltest.TEST_TMPDIR.value)
    coordinates = [(178.482925, -16.632893), (178.482283, -16.632279)]
    generate_examples.generate_examples_pipeline(
        before_image_path=self.test_image_path,
        after_image_path=self.test_image_path,
        large_patch_size=32,
        example_patch_size=32,
        resolution=0.5,
        output_dir=output_dir,
        num_output_shards=1,
        unlabeled_coordinates=coordinates,
        labeled_coordinates=[],
        use_dataflow=False,
        num_labeling_images=0,
        gdal_env={},
        dataflow_job_name='test',
        dataflow_container_image=None,
        cloud_project=None,
        cloud_region=None,
        worker_service_account=None,
        max_workers=0)

    tfrecords = os.listdir(os.path.join(output_dir, 'examples', 'unlabeled'))
    self.assertSameElements(tfrecords, ['unlabeled-00000-of-00001.tfrecord'])


if __name__ == '__main__':
  absltest.main()
